### Aggregate data by user

In [ ]:
import pandas as pd

path = "human_likeness/human_likeness_all_models_clean.csv"

df = pd.read_csv(path, index_col=False)

df["user"] = df["id"].str.split("p").str[0]

df_mean = (
    df.groupby("user", as_index=False)
      .agg({
          "social_class": "first",
          **{col: "mean" for col in df.select_dtypes(include="number").columns}
      })
)

df_mean

,user,social_class,ses,humt_responses_qwen-3.5-27B,sociot_status_responses_qwen-3.5-27B,sociot_social_distance_responses_qwen-3.5-27B,sociot_gender_responses_qwen-3.5-27B,sociot_warmth_responses_qwen-3.5-27B,humt_responses_llama-3.3-70B,sociot_status_responses_llama-3.3-70B,...,humt_responses_gemma-4-31B,sociot_status_responses_gemma-4-31B,sociot_social_distance_responses_gemma-4-31B,sociot_gender_responses_gemma-4-31B,sociot_warmth_responses_gemma-4-31B,humt_responses_gpt-5.5,sociot_status_responses_gpt-5.5,sociot_social_distance_responses_gpt-5.5,sociot_gender_responses_gpt-5.5,sociot_warmth_responses_gpt-5.5
0,u1,upper,8.0,0.023095,-0.071759,0.073158,0.012857,0.025321,0.029543,-0.041021,...,0.035555,-0.073451,0.051445,0.003853,0.026388,0.026588,-0.071523,0.055837,-0.007194,0.032771
1,u10,middle,4.0,-0.020594,-0.060516,0.045889,0.024098,0.025284,0.025996,-0.063820,...,0.006662,-0.048932,0.028511,0.007058,0.005875,-0.013669,-0.053564,0.037663,0.018229,0.005928
2,u100,middle,5.0,0.001084,-0.045402,0.021460,-0.008554,-0.005779,0.013286,-0.036912,...,-0.002399,-0.069821,0.005718,0.005792,-0.005846,-0.019104,-0.049906,0.013498,-0.006666,0.028179
3,u101,middle,7.0,0.010785,-0.065784,0.059077,0.024418,0.030944,0.018736,-0.053815,...,0.029042,-0.044767,0.040755,0.006951,0.024419,0.036460,-0.066811,0.057152,0.022686,0.029121
4,u104,middle,5.0,-0.006946,0.005192,0.002667,0.029539,0.021212,-0.002470,-0.013435,...,0.019086,0.031629,0.074310,0.013099,0.006654,0.031680,-0.007167,0.075585,0.016762,0.020009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,u994,middle,4.0,0.020746,-0.048700,0.038126,0.002927,0.003825,0.020935,-0.068979,...,-0.010703,-0.058445,0.042872,0.021268,-0.009568,0.016200,-0.059726,0.043854,-0.009267,0.006764
728,u996,middle,6.0,0.006689,-0.043185,0.031113,0.005224,0.006343,0.009714,-0.074827,...,0.003875,-0.041901,0.045710,0.015735,0.026032,0.017302,-0.056645,0.059477,0.018574,0.031757
729,u997,middle,6.0,0.009798,-0.027808,0.023699,-0.045855,0.000295,0.038351,-0.059886,...,-0.015686,-0.016756,0.028371,0.032977,0.009479,0.024165,-0.066406,0.056226,0.020184,0.054182
730,u998,low,2.0,0.020126,-0.054790,0.041039,-0.000599,0.033423,0.028342,-0.060776,...,0.027581,-0.050413,0.051339,0.001814,0.043262,0.005279,-0.050731,0.047337,0.017544,0.037201
731,u999,upper,9.0,0.014284,-0.048089,0.027905,-0.007969,0.007494,0.004655,-0.047940,...,0.011038,-0.042151,0.033171,-0.008276,-0.000628,-0.010716,-0.040062,0.011102,-0.014943,0.003057

In [10]:
df_mean["social_class"].value_counts()

social_class
middle    406
low       214
upper     112
Name: count, dtype: int64

### Statistical Testing

In [1]:
import pandas as pd

path = "all_metrics/all_metrics_per_user.csv"

df = pd.read_csv(path, index_col=False)

cols = list(df.columns)

In [2]:
exclude = ['user',
 'social_class',
 'gender',
 'gender_other',
 'age',
 'nationality',
 'ethnicity',
 'ethnicity_other',
 'marital',
 'marital_other',
 'language',
 'language_other',
 'religion',
 'religion_other',
 'education',
 'mum_education',
 'dad_education',
 'home',
 'home_other',
 'employment',
 'occupation',
 'mother_occupation',
 'father_occupation',
 'hobbies',
 'hobbies_other',
 'tech',
 'tech_other',
 'know_nlp',
 'know_nlp_other',
 'use_nlp',
 'use_nlp_other',
 'would_nlp',
 'would_nlp_other',
 'frequency_llm',
 'llm_use',
 'llm_other',
 'usecases',
 'usecases_other',
 'contexts',
 'contexts_other',
 'comments',
 'ses']

cols_rel = [col for col in cols if not col in exclude]
cols_rel = [col for col in cols_rel if not col.startswith("std")]
#cols_rel = [col for col in cols_rel if not col.startswith("cplx")] # cplx ling hlepfulness
cols_rel = [col for col in cols_rel if not col.startswith("ling")]
cols_rel = [col for col in cols_rel if not col.startswith("helpfulness")]

complexity = ["average_age_of_acquisition", 
              "conceptual_graph_ontology_number_of_concpets",
              "dale_chall_readability_score",
              "gunning_fog_index",
              "word_concreteness",
              "average_cefr_level",
              "mean_word_length",
              "passive_constructions_density",
              "connectives"]

linguistic = ["avg_valence", 
        "avg_arousal",
        "avg_dominance",
        "avg_intensity_anger",
        "avg_intensity_anticipation",
        "avg_intensity_disgust",
        "avg_intensity_fear",
        "avg_intensity_joy",
        "avg_intensity_sadness",
        "avg_intensity_surprise",
        "avg_intensity_trust",
        "sentiment_score"]

models = ["gemma-4-31B", "llama-3.3-70B", "qwen-3.5-27B", "gpt-5.5"]

ling = [f"ling_{l}_{m}" for l in linguistic for m in models]
#cplx = [f"cplx_{c}_{m}" for c in complexity for m in models]

cols_rel = cols_rel + ling

cols_rel

['normalized_helpfulness_responses_qwen-3.5-27B',
 'normalized_helpfulness_responses_llama-3.3-70B',
 'normalized_helpfulness_responses_gemma-4-31B',
 'normalized_helpfulness_responses_gpt-5.5',
 'humt_responses_qwen-3.5-27B',
 'sociot_status_responses_qwen-3.5-27B',
 'sociot_social_distance_responses_qwen-3.5-27B',
 'sociot_gender_responses_qwen-3.5-27B',
 'sociot_warmth_responses_qwen-3.5-27B',
 'humt_responses_llama-3.3-70B',
 'sociot_status_responses_llama-3.3-70B',
 'sociot_social_distance_responses_llama-3.3-70B',
 'sociot_gender_responses_llama-3.3-70B',
 'sociot_warmth_responses_llama-3.3-70B',
 'humt_responses_gemma-4-31B',
 'sociot_status_responses_gemma-4-31B',
 'sociot_social_distance_responses_gemma-4-31B',
 'sociot_gender_responses_gemma-4-31B',
 'sociot_warmth_responses_gemma-4-31B',
 'humt_responses_gpt-5.5',
 'sociot_status_responses_gpt-5.5',
 'sociot_social_distance_responses_gpt-5.5',
 'sociot_gender_responses_gpt-5.5',
 'sociot_warmth_responses_gpt-5.5',
 'cplx_additive_connectives_gemma-4-31B',
 'cplx_adjectives_density_gemma-4-31B',
 'cplx_adverbs_density_gemma-4-31B',
 'cplx_adversative_connectives_gemma-4-31B',
 'cplx_argument_overlap_adjacent_gemma-4-31B',
 'cplx_argument_overlap_all_gemma-4-31B',
 'cplx_average_age_of_acquisition_gemma-4-31B',
 'cplx_average_cefr_level_gemma-4-31B',
 'cplx_average_concreteness_gemma-4-31B',
 'cplx_average_familiarity_gemma-4-31B',
 'cplx_average_imagery_gemma-4-31B',
 'cplx_average_meaningfulness_gemma-4-31B',
 'cplx_average_number_of_clauses_per_sentence_gemma-4-31B',
 'cplx_average_number_of_commas_per_sentence_gemma-4-31B',
 'cplx_average_number_of_meaning_per_word_gemma-4-31B',
 'cplx_average_sentence_length_gemma-4-31B',
 'cplx_causal_connectives_gemma-4-31B',
 'cplx_coca_academic_range_gemma-4-31B',
 'cplx_coleman_liau_index_gemma-4-31B',
 'cplx_concept_density_concepts_per_sentence_gemma-4-31B',
 'cplx_conceptual_graph_ontology_number_of_concpets_gemma-4-31B',
 'cplx_conceptual_graph_ontology_number_of_distinct_concepts_gemma-4-31B',
 'cplx_connectives_gemma-4-31B',
 'cplx_content_word_frequency_log_gemma-4-31B',
 'cplx_content_word_overlap_adjacent_gemma-4-31B',
 'cplx_content_word_overlap_all_gemma-4-31B',
 'cplx_dale_chall_readability_score_gemma-4-31B',
 'cplx_dependency_parser_branching_gemma-4-31B',
 'cplx_dependency_parser_dependency_distance_gemma-4-31B',
 'cplx_dependency_parser_tree_depth_gemma-4-31B',
 'cplx_dissimilarity_of_words_between_sentences_gemma-4-31B',
 'cplx_first_person_pronouns_density_gemma-4-31B',
 'cplx_flesch_kincaid_grade_level_gemma-4-31B',
 'cplx_gunning_fog_index_gemma-4-31B',
 'cplx_knowledge_graph_average_node_pagerank_gemma-4-31B',
 'cplx_knowledge_graph_number_of_connected_components_gemma-4-31B',
 'cplx_linsear_write_formula_gemma-4-31B',
 'cplx_logical_connectives_gemma-4-31B',
 'cplx_mattr_gemma-4-31B',
 'cplx_max_kuperman_age_of_acquisition_gemma-4-31B',
 'cplx_max_number_of_clauses_per_sentence_gemma-4-31B',
 'cplx_max_number_of_if_per_sentence_gemma-4-31B',
 'cplx_max_number_of_wh_clauses_per_sentence_gemma-4-31B',
 'cplx_mean_word_length_gemma-4-31B',
 'cplx_median_kuperman_age_of_acquisition_gemma-4-31B',
 'cplx_modifiers_per_noun_phrase_gemma-4-31B',
 'cplx_negations_density_gemma-4-31B',
 'cplx_noun_overlap_adjacent_gemma-4-31B',
 'cplx_nouns_density_gemma-4-31B',
 'cplx_number_of_connectives_gemma-4-31B',
 'cplx_number_of_connectives_per_3_sentence_sliding_window_gemma-4-31B',
 'cplx_number_of_wordnet_hypernyms_per_word_gemma-4-31B',
 'cplx_number_of_wordnet_hyponyms_per_word_gemma-4-31B',
 'cplx_overlap_between_adjacent_sents_based_on_argument_bearing_words_gemma-4-31B',
 'cplx_passive_constructions_density_gemma-4-31B',
 'cplx_percentage_of_words_above_b1_level_gemma-4-31B',
 'cplx_percentage_of_words_with_more_than_5_meanings_gemma-4-31B',
 'cplx_polysemy_gemma-4-31B',
 'cplx_pos_dissimilarity_between_sentences_gemma-4-31B',
 'cplx_pronouns_density_gemma-4-31B',
 'cplx_reading_time_gemma-4-31B',
 'cplx_stem_overlap_sent_gemma-4-31B',
 'cplx_syllables_per_word_gemma-4-31B',
 'cplx_te_score_gemma-4-31B',
 'cplx_temporal_cohesions_gemma-4-31B',
 'cplx_temporal_connectives_gemma-4-31B',
 'cplx_text_length_gemma-4-31B',
 'cplx_third_person_pronouns_density_gemma-4-31B',
 'cplx_type_token_ratio_gemma-4-31B',
 'cplx_verb_aspect_repetition_gemma-4-31B',
 'cplx_verb_overlap_adjacent_gemma-4-31B',
 'cplx_verb_tense_repetition_gemma-4-31B',
 'cplx_verb_tense_repetition_nltk_gemma-4-31B',
 'cplx_verb_ttr_gemma-4-31B',
 'cplx_verb_ttr_adj_gemma-4-31B',
 'cplx_verbs_density_gemma-4-31B',
 'cplx_word_concreteness_gemma-4-31B',
 'cplx_word_frequency_log_gemma-4-31B',
 'cplx_additive_connectives_gpt-5.5',
 'cplx_adjectives_density_gpt-5.5',
 'cplx_adverbs_density_gpt-5.5',
 'cplx_adversative_connectives_gpt-5.5',
 'cplx_argument_overlap_adjacent_gpt-5.5',
 'cplx_argument_overlap_all_gpt-5.5',
 'cplx_average_age_of_acquisition_gpt-5.5',
 'cplx_average_cefr_level_gpt-5.5',
 'cplx_average_concreteness_gpt-5.5',
 'cplx_average_familiarity_gpt-5.5',
 'cplx_average_imagery_gpt-5.5',
 'cplx_average_meaningfulness_gpt-5.5',
 'cplx_average_number_of_clauses_per_sentence_gpt-5.5',
 'cplx_average_number_of_commas_per_sentence_gpt-5.5',
 'cplx_average_number_of_meaning_per_word_gpt-5.5',
 'cplx_average_sentence_length_gpt-5.5',
 'cplx_causal_connectives_gpt-5.5',
 'cplx_coca_academic_range_gpt-5.5',
 'cplx_coleman_liau_index_gpt-5.5',
 'cplx_concept_density_concepts_per_sentence_gpt-5.5',
 'cplx_conceptual_graph_ontology_number_of_concpets_gpt-5.5',
 'cplx_conceptual_graph_ontology_number_of_distinct_concepts_gpt-5.5',
 'cplx_connectives_gpt-5.5',
 'cplx_content_word_frequency_log_gpt-5.5',
 'cplx_content_word_overlap_adjacent_gpt-5.5',
 'cplx_content_word_overlap_all_gpt-5.5',
 'cplx_dale_chall_readability_score_gpt-5.5',
 'cplx_dependency_parser_branching_gpt-5.5',
 'cplx_dependency_parser_dependency_distance_gpt-5.5',
 'cplx_dependency_parser_tree_depth_gpt-5.5',
 'cplx_dissimilarity_of_words_between_sentences_gpt-5.5',
 'cplx_first_person_pronouns_density_gpt-5.5',
 'cplx_flesch_kincaid_grade_level_gpt-5.5',
 'cplx_gunning_fog_index_gpt-5.5',
 'cplx_knowledge_graph_average_node_pagerank_gpt-5.5',
 'cplx_knowledge_graph_number_of_connected_components_gpt-5.5',
 'cplx_linsear_write_formula_gpt-5.5',
 'cplx_logical_connectives_gpt-5.5',
 'cplx_mattr_gpt-5.5',
 'cplx_max_kuperman_age_of_acquisition_gpt-5.5',
 'cplx_max_number_of_clauses_per_sentence_gpt-5.5',
 'cplx_max_number_of_if_per_sentence_gpt-5.5',
 'cplx_max_number_of_wh_clauses_per_sentence_gpt-5.5',
 'cplx_mean_word_length_gpt-5.5',
 'cplx_median_kuperman_age_of_acquisition_gpt-5.5',
 'cplx_modifiers_per_noun_phrase_gpt-5.5',
 'cplx_negations_density_gpt-5.5',
 'cplx_noun_overlap_adjacent_gpt-5.5',
 'cplx_nouns_density_gpt-5.5',
 'cplx_number_of_connectives_gpt-5.5',
 'cplx_number_of_connectives_per_3_sentence_sliding_window_gpt-5.5',
 'cplx_number_of_wordnet_hypernyms_per_word_gpt-5.5',
 'cplx_number_of_wordnet_hyponyms_per_word_gpt-5.5',
 'cplx_overlap_between_adjacent_sents_based_on_argument_bearing_words_gpt-5.5',
 'cplx_passive_constructions_density_gpt-5.5',
 'cplx_percentage_of_words_above_b1_level_gpt-5.5',
 'cplx_percentage_of_words_with_more_than_5_meanings_gpt-5.5',
 'cplx_polysemy_gpt-5.5',
 'cplx_pos_dissimilarity_between_sentences_gpt-5.5',
 'cplx_pronouns_density_gpt-5.5',
 'cplx_reading_time_gpt-5.5',
 'cplx_stem_overlap_sent_gpt-5.5',
 'cplx_syllables_per_word_gpt-5.5',
 'cplx_te_score_gpt-5.5',
 'cplx_temporal_cohesions_gpt-5.5',
 'cplx_temporal_connectives_gpt-5.5',
 'cplx_text_length_gpt-5.5',
 'cplx_third_person_pronouns_density_gpt-5.5',
 'cplx_type_token_ratio_gpt-5.5',
 'cplx_verb_aspect_repetition_gpt-5.5',
 'cplx_verb_overlap_adjacent_gpt-5.5',
 'cplx_verb_tense_repetition_gpt-5.5',
 'cplx_verb_tense_repetition_nltk_gpt-5.5',
 'cplx_verb_ttr_gpt-5.5',
 'cplx_verb_ttr_adj_gpt-5.5',
 'cplx_verbs_density_gpt-5.5',
 'cplx_word_concreteness_gpt-5.5',
 'cplx_word_frequency_log_gpt-5.5',
 'cplx_additive_connectives_llama-3.3-70B',
 'cplx_adjectives_density_llama-3.3-70B',
 'cplx_adverbs_density_llama-3.3-70B',
 'cplx_adversative_connectives_llama-3.3-70B',
 'cplx_argument_overlap_adjacent_llama-3.3-70B',
 'cplx_argument_overlap_all_llama-3.3-70B',
 'cplx_average_age_of_acquisition_llama-3.3-70B',
 'cplx_average_cefr_level_llama-3.3-70B',
 'cplx_average_concreteness_llama-3.3-70B',
 'cplx_average_familiarity_llama-3.3-70B',
 'cplx_average_imagery_llama-3.3-70B',
 'cplx_average_meaningfulness_llama-3.3-70B',
 'cplx_average_number_of_clauses_per_sentence_llama-3.3-70B',
 'cplx_average_number_of_commas_per_sentence_llama-3.3-70B',
 'cplx_average_number_of_meaning_per_word_llama-3.3-70B',
 'cplx_average_sentence_length_llama-3.3-70B',
 'cplx_causal_connectives_llama-3.3-70B',
 'cplx_coca_academic_range_llama-3.3-70B',
 'cplx_coleman_liau_index_llama-3.3-70B',
 'cplx_concept_density_concepts_per_sentence_llama-3.3-70B',
 'cplx_conceptual_graph_ontology_number_of_concpets_llama-3.3-70B',
 'cplx_conceptual_graph_ontology_number_of_distinct_concepts_llama-3.3-70B',
 'cplx_connectives_llama-3.3-70B',
 'cplx_content_word_frequency_log_llama-3.3-70B',
 'cplx_content_word_overlap_adjacent_llama-3.3-70B',
 'cplx_content_word_overlap_all_llama-3.3-70B',
 'cplx_dale_chall_readability_score_llama-3.3-70B',
 'cplx_dependency_parser_branching_llama-3.3-70B',
 'cplx_dependency_parser_dependency_distance_llama-3.3-70B',
 'cplx_dependency_parser_tree_depth_llama-3.3-70B',
 'cplx_dissimilarity_of_words_between_sentences_llama-3.3-70B',
 'cplx_first_person_pronouns_density_llama-3.3-70B',
 'cplx_flesch_kincaid_grade_level_llama-3.3-70B',
 'cplx_gunning_fog_index_llama-3.3-70B',
 'cplx_knowledge_graph_average_node_pagerank_llama-3.3-70B',
 'cplx_knowledge_graph_number_of_connected_components_llama-3.3-70B',
 'cplx_linsear_write_formula_llama-3.3-70B',
 'cplx_logical_connectives_llama-3.3-70B',
 'cplx_mattr_llama-3.3-70B',
 'cplx_max_kuperman_age_of_acquisition_llama-3.3-70B',
 'cplx_max_number_of_clauses_per_sentence_llama-3.3-70B',
 'cplx_max_number_of_if_per_sentence_llama-3.3-70B',
 'cplx_max_number_of_wh_clauses_per_sentence_llama-3.3-70B',
 'cplx_mean_word_length_llama-3.3-70B',
 'cplx_median_kuperman_age_of_acquisition_llama-3.3-70B',
 'cplx_modifiers_per_noun_phrase_llama-3.3-70B',
 'cplx_negations_density_llama-3.3-70B',
 'cplx_noun_overlap_adjacent_llama-3.3-70B',
 'cplx_nouns_density_llama-3.3-70B',
 'cplx_number_of_connectives_llama-3.3-70B',
 'cplx_number_of_connectives_per_3_sentence_sliding_window_llama-3.3-70B',
 'cplx_number_of_wordnet_hypernyms_per_word_llama-3.3-70B',
 'cplx_number_of_wordnet_hyponyms_per_word_llama-3.3-70B',
 'cplx_overlap_between_adjacent_sents_based_on_argument_bearing_words_llama-3.3-70B',
 'cplx_passive_constructions_density_llama-3.3-70B',
 'cplx_percentage_of_words_above_b1_level_llama-3.3-70B',
 'cplx_percentage_of_words_with_more_than_5_meanings_llama-3.3-70B',
 'cplx_polysemy_llama-3.3-70B',
 'cplx_pos_dissimilarity_between_sentences_llama-3.3-70B',
 'cplx_pronouns_density_llama-3.3-70B',
 'cplx_reading_time_llama-3.3-70B',
 'cplx_stem_overlap_sent_llama-3.3-70B',
 'cplx_syllables_per_word_llama-3.3-70B',
 'cplx_te_score_llama-3.3-70B',
 'cplx_temporal_cohesions_llama-3.3-70B',
 'cplx_temporal_connectives_llama-3.3-70B',
 'cplx_text_length_llama-3.3-70B',
 'cplx_third_person_pronouns_density_llama-3.3-70B',
 'cplx_type_token_ratio_llama-3.3-70B',
 'cplx_verb_aspect_repetition_llama-3.3-70B',
 'cplx_verb_overlap_adjacent_llama-3.3-70B',
 'cplx_verb_tense_repetition_llama-3.3-70B',
 'cplx_verb_tense_repetition_nltk_llama-3.3-70B',
 'cplx_verb_ttr_llama-3.3-70B',
 'cplx_verb_ttr_adj_llama-3.3-70B',
 'cplx_verbs_density_llama-3.3-70B',
 'cplx_word_concreteness_llama-3.3-70B',
 'cplx_word_frequency_log_llama-3.3-70B',
 'cplx_additive_connectives_qwen-3.5-27B',
 'cplx_adjectives_density_qwen-3.5-27B',
 'cplx_adverbs_density_qwen-3.5-27B',
 'cplx_adversative_connectives_qwen-3.5-27B',
 'cplx_argument_overlap_adjacent_qwen-3.5-27B',
 'cplx_argument_overlap_all_qwen-3.5-27B',
 'cplx_average_age_of_acquisition_qwen-3.5-27B',
 'cplx_average_cefr_level_qwen-3.5-27B',
 'cplx_average_concreteness_qwen-3.5-27B',
 'cplx_average_familiarity_qwen-3.5-27B',
 'cplx_average_imagery_qwen-3.5-27B',
 'cplx_average_meaningfulness_qwen-3.5-27B',
 'cplx_average_number_of_clauses_per_sentence_qwen-3.5-27B',
 'cplx_average_number_of_commas_per_sentence_qwen-3.5-27B',
 'cplx_average_number_of_meaning_per_word_qwen-3.5-27B',
 'cplx_average_sentence_length_qwen-3.5-27B',
 'cplx_causal_connectives_qwen-3.5-27B',
 'cplx_coca_academic_range_qwen-3.5-27B',
 'cplx_coleman_liau_index_qwen-3.5-27B',
 'cplx_concept_density_concepts_per_sentence_qwen-3.5-27B',
 'cplx_conceptual_graph_ontology_number_of_concpets_qwen-3.5-27B',
 'cplx_conceptual_graph_ontology_number_of_distinct_concepts_qwen-3.5-27B',
 'cplx_connectives_qwen-3.5-27B',
 'cplx_content_word_frequency_log_qwen-3.5-27B',
 'cplx_content_word_overlap_adjacent_qwen-3.5-27B',
 'cplx_content_word_overlap_all_qwen-3.5-27B',
 'cplx_dale_chall_readability_score_qwen-3.5-27B',
 'cplx_dependency_parser_branching_qwen-3.5-27B',
 'cplx_dependency_parser_dependency_distance_qwen-3.5-27B',
 'cplx_dependency_parser_tree_depth_qwen-3.5-27B',
 'cplx_dissimilarity_of_words_between_sentences_qwen-3.5-27B',
 'cplx_first_person_pronouns_density_qwen-3.5-27B',
 'cplx_flesch_kincaid_grade_level_qwen-3.5-27B',
 'cplx_gunning_fog_index_qwen-3.5-27B',
 'cplx_knowledge_graph_average_node_pagerank_qwen-3.5-27B',
 'cplx_knowledge_graph_number_of_connected_components_qwen-3.5-27B',
 'cplx_linsear_write_formula_qwen-3.5-27B',
 'cplx_logical_connectives_qwen-3.5-27B',
 'cplx_mattr_qwen-3.5-27B',
 'cplx_max_kuperman_age_of_acquisition_qwen-3.5-27B',
 'cplx_max_number_of_clauses_per_sentence_qwen-3.5-27B',
 'cplx_max_number_of_if_per_sentence_qwen-3.5-27B',
 'cplx_max_number_of_wh_clauses_per_sentence_qwen-3.5-27B',
 'cplx_mean_word_length_qwen-3.5-27B',
 'cplx_median_kuperman_age_of_acquisition_qwen-3.5-27B',
 'cplx_modifiers_per_noun_phrase_qwen-3.5-27B',
 'cplx_negations_density_qwen-3.5-27B',
 'cplx_noun_overlap_adjacent_qwen-3.5-27B',
 'cplx_nouns_density_qwen-3.5-27B',
 'cplx_number_of_connectives_qwen-3.5-27B',
 'cplx_number_of_connectives_per_3_sentence_sliding_window_qwen-3.5-27B',
 'cplx_number_of_wordnet_hypernyms_per_word_qwen-3.5-27B',
 'cplx_number_of_wordnet_hyponyms_per_word_qwen-3.5-27B',
 'cplx_overlap_between_adjacent_sents_based_on_argument_bearing_words_qwen-3.5-27B',
 'cplx_passive_constructions_density_qwen-3.5-27B',
 'cplx_percentage_of_words_above_b1_level_qwen-3.5-27B',
 'cplx_percentage_of_words_with_more_than_5_meanings_qwen-3.5-27B',
 'cplx_polysemy_qwen-3.5-27B',
 'cplx_pos_dissimilarity_between_sentences_qwen-3.5-27B',
 'cplx_pronouns_density_qwen-3.5-27B',
 'cplx_reading_time_qwen-3.5-27B',
 'cplx_stem_overlap_sent_qwen-3.5-27B',
 'cplx_syllables_per_word_qwen-3.5-27B',
 'cplx_te_score_qwen-3.5-27B',
 'cplx_temporal_cohesions_qwen-3.5-27B',
 'cplx_temporal_connectives_qwen-3.5-27B',
 'cplx_text_length_qwen-3.5-27B',
 'cplx_third_person_pronouns_density_qwen-3.5-27B',
 'cplx_type_token_ratio_qwen-3.5-27B',
 'cplx_verb_aspect_repetition_qwen-3.5-27B',
 'cplx_verb_overlap_adjacent_qwen-3.5-27B',
 'cplx_verb_tense_repetition_qwen-3.5-27B',
 'cplx_verb_tense_repetition_nltk_qwen-3.5-27B',
 'cplx_verb_ttr_qwen-3.5-27B',
 'cplx_verb_ttr_adj_qwen-3.5-27B',
 'cplx_verbs_density_qwen-3.5-27B',
 'cplx_word_concreteness_qwen-3.5-27B',
 'cplx_word_frequency_log_qwen-3.5-27B',
 'syco_framing_qwen-3.5-27B',
 'syco_framing_llama-3.3-70B',
 'syco_framing_gemma-4-31B',
 'syco_framing_gpt-5.5',
 'syco_validation_qwen-3.5-27B',
 'syco_validation_llama-3.3-70B',
 'syco_validation_gemma-4-31B',
 'syco_validation_gpt-5.5',
 'syco_indirectness_qwen-3.5-27B',
 'syco_indirectness_llama-3.3-70B',
 'syco_indirectness_gemma-4-31B',
 'syco_indirectness_gpt-5.5',
 'ling_avg_valence_gemma-4-31B',
 'ling_avg_valence_llama-3.3-70B',
 'ling_avg_valence_qwen-3.5-27B',
 'ling_avg_valence_gpt-5.5',
 'ling_avg_arousal_gemma-4-31B',
 'ling_avg_arousal_llama-3.3-70B',
 'ling_avg_arousal_qwen-3.5-27B',
 'ling_avg_arousal_gpt-5.5',
 'ling_avg_dominance_gemma-4-31B',
 'ling_avg_dominance_llama-3.3-70B',
 'ling_avg_dominance_qwen-3.5-27B',
 'ling_avg_dominance_gpt-5.5',
 'ling_avg_intensity_anger_gemma-4-31B',
 'ling_avg_intensity_anger_llama-3.3-70B',
 'ling_avg_intensity_anger_qwen-3.5-27B',
 'ling_avg_intensity_anger_gpt-5.5',
 'ling_avg_intensity_anticipation_gemma-4-31B',
 'ling_avg_intensity_anticipation_llama-3.3-70B',
 'ling_avg_intensity_anticipation_qwen-3.5-27B',
 'ling_avg_intensity_anticipation_gpt-5.5',
 'ling_avg_intensity_disgust_gemma-4-31B',
 'ling_avg_intensity_disgust_llama-3.3-70B',
 'ling_avg_intensity_disgust_qwen-3.5-27B',
 'ling_avg_intensity_disgust_gpt-5.5',
 'ling_avg_intensity_fear_gemma-4-31B',
 'ling_avg_intensity_fear_llama-3.3-70B',
 'ling_avg_intensity_fear_qwen-3.5-27B',
 'ling_avg_intensity_fear_gpt-5.5',
 'ling_avg_intensity_joy_gemma-4-31B',
 'ling_avg_intensity_joy_llama-3.3-70B',
 'ling_avg_intensity_joy_qwen-3.5-27B',
 'ling_avg_intensity_joy_gpt-5.5',
 'ling_avg_intensity_sadness_gemma-4-31B',
 'ling_avg_intensity_sadness_llama-3.3-70B',
 'ling_avg_intensity_sadness_qwen-3.5-27B',
 'ling_avg_intensity_sadness_gpt-5.5',
 'ling_avg_intensity_surprise_gemma-4-31B',
 'ling_avg_intensity_surprise_llama-3.3-70B',
 'ling_avg_intensity_surprise_qwen-3.5-27B',
 'ling_avg_intensity_surprise_gpt-5.5',
 'ling_avg_intensity_trust_gemma-4-31B',
 'ling_avg_intensity_trust_llama-3.3-70B',
 'ling_avg_intensity_trust_qwen-3.5-27B',
 'ling_avg_intensity_trust_gpt-5.5',
 'ling_sentiment_score_gemma-4-31B',
 'ling_sentiment_score_llama-3.3-70B',
 'ling_sentiment_score_qwen-3.5-27B',
 'ling_sentiment_score_gpt-5.5']

In [4]:
import pandas as pd
import numpy as np
from scipy import stats
import scikit_posthocs as sp
from statsmodels.stats.multitest import multipletests

order = ['low', 'middle', 'upper']
measures = cols_rel

def cliffs_delta(x, y):
    x, y = np.array(x), np.array(y)
    diff = x[:, None] - y[None, :]
    return (np.sum(diff > 0) - np.sum(diff < 0)) / (len(x) * len(y))

rows = []
for measure in measures:
    sub = df.dropna(subset=[measure])
    groups = [sub.loc[sub['social_class'] == lvl, measure] for lvl in order]

    h_stat, p_omnibus = stats.kruskal(*groups)
    n = sum(len(g) for g in groups)
    eps_sq = h_stat / ((n**2 - 1) / (n + 1))

    # Dunn's test, Holm-corrected WITHIN this measure's 3 pairs
    dunn_p = sp.posthoc_dunn(sub, val_col=measure, group_col='social_class', p_adjust='holm')

    pairs = [('low', 'middle'), ('low', 'upper'), ('middle', 'upper')]
    for g1, g2 in pairs:
        x = sub.loc[sub['social_class'] == g1, measure]
        y = sub.loc[sub['social_class'] == g2, measure]
        delta = cliffs_delta(x, y)
        direction = g1 if delta > 0 else (g2 if delta < 0 else "tie")

        rows.append({
            'measure': measure,
            'p_omnibus': p_omnibus,
            'epsilon_squared': eps_sq,
            'comparison': f'{g1} vs {g2}',
            'dunn_p_holm': dunn_p.loc[g1, g2],   # <-- significance for this pair
            'cliffs_delta': delta,               # <-- magnitude + direction
            'higher_group': direction,
        })

results = pd.DataFrame(rows)

# --- Correction 1: omnibus p across all measures ---
#omnibus_unique = results.drop_duplicates('measure')[['measure', 'p_omnibus']]
#_, p_fdr, _, _ = multipletests(omnibus_unique['p_omnibus'], method='fdr_bh')
#omnibus_unique['p_omnibus_fdr'] = p_fdr
#results = results.merge(omnibus_unique[['measure', 'p_omnibus_fdr']], on='measure')

# --- Correction 2: pairwise dunn_p across ALL rows (all measures x all pairs) ---
#_, dunn_p_fdr, _, _ = multipletests(results['dunn_p_holm'], method='fdr_bh')
#results['dunn_p_fdr'] = dunn_p_fdr

# --- Flag: is this specific pairwise comparison significant AND meaningful? ---
def flag_pair(row):
    if row['p_omnibus'] >= 0.05:
        return 'omnibus not significant'
    elif row['dunn_p_holm'] >= 0.05:
        return 'no significant difference (pair)'
    else:
        return 'significant difference (pair)'
    
    #elif abs(row['cliffs_delta']) < 0.147:
    #    return 'significant but negligible'
    #else:
    #    return 'significant and meaningful'

results['pair_flag'] = results.apply(flag_pair, axis=1)

results['pair_flag'] = results.apply(flag_pair, axis=1)

results = results[['measure', 'p_omnibus', 'epsilon_squared', # 'p_omnibus_fdr',
                    'comparison', 'dunn_p_holm', 'cliffs_delta', 'higher_group', 'pair_flag']] # 'dunn_p_fdr',

results

,measure,p_omnibus,epsilon_squared,comparison,dunn_p_holm,cliffs_delta,higher_group,pair_flag
0,normalized_helpfulness_responses_qwen-3.5-27B,0.112036,0.005989,low vs middle,0.332234,-0.052208,middle,omnibus not significant
1,normalized_helpfulness_responses_qwen-3.5-27B,0.112036,0.005989,low vs upper,0.110884,-0.151327,upper,omnibus not significant
2,normalized_helpfulness_responses_qwen-3.5-27B,0.112036,0.005989,middle vs upper,0.332234,-0.079719,upper,omnibus not significant
3,normalized_helpfulness_responses_llama-3.3-70B,0.031422,0.009467,low vs middle,0.211209,-0.073316,middle,no significant difference (pair)
4,normalized_helpfulness_responses_llama-3.3-70B,0.031422,0.009467,low vs upper,0.027489,-0.184579,upper,significant difference (pair)
...,...,...,...,...,...,...,...,...
1183,ling_sentiment_score_qwen-3.5-27B,0.077464,0.006998,low vs upper,0.088635,-0.152203,upper,omnibus not significant
1184,ling_sentiment_score_qwen-3.5-27B,0.077464,0.006998,middle vs upper,0.093044,-0.119810,upper,omnibus not significant
1185,ling_sentiment_score_gpt-5.5,0.041350,0.008764,low vs middle,0.252702,-0.054897,middle,no significant difference (pair)
1186,ling_sentiment_score_gpt-5.5,0.041350,0.008764,low vs upper,0.034860,-0.174513,upper,significant difference (pair)
1187,ling_sentiment_score_gpt-5.5,0.041350,0.008764,middle vs upper,0.127825,-0.112680,upper,no significant difference (pair)

In [6]:
results.to_csv("all_group_differences.csv", index=False)

In [9]:
print(f"Number of KW tests: {len(results)/3}")
print(f'Significant differences between groups: {(len(results) - len(results[results["pair_flag"] == "omnibus not significant"]))/3}')
print()
print(f'Significant differences between pairs of groups: {len(results[results["pair_flag"] == "significant difference (pair)"])} out of {len(results)}')

Number of KW tests: 396.0
Significant differences between groups: 109.0

Significant differences between pairs of groups: 156 out of 1188

In [10]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.multitest import multipletests

measures = cols_rel

def cliffs_delta(x, y):
    x, y = np.array(x), np.array(y)
    diff = x[:, None] - y[None, :]
    return (np.sum(diff > 0) - np.sum(diff < 0)) / (len(x) * len(y))

rows = []
for measure in measures:
    sub = df.dropna(subset=[measure])
    x = sub.loc[sub['social_class'] == 'upper', measure]
    y = sub.loc[sub['social_class'] == 'low', measure]

    stat, p = stats.mannwhitneyu(x, y, alternative='two-sided')
    delta = cliffs_delta(x, y)
    direction = 'upper' if delta > 0 else ('low' if delta < 0 else 'tie')

    rows.append({
        'measure': measure,
        'p_value': p,
        'cliffs_delta': delta,
        'higher_group': direction,
    })

results = pd.DataFrame(rows)

# Correct across all 100+ measures
#_, p_fdr, _, _ = multipletests(results['p_value'], method='fdr_bh')
#results['p_fdr'] = p_fdr

# Simple flag combining significance + meaningful magnitude
def flag(row):
    if row['p_value'] >= 0.05:
        return 'no significant difference'
    else:
        return "significant difference"
    
    #elif abs(row['cliffs_delta']) < 0.147:  # negligible threshold (Romano et al.)
    #    return 'significant but negligible'
    #else:
    #    return 'significant and meaningful'

results['flag'] = results.apply(flag, axis=1)

results = results[['measure', 'p_value', 'cliffs_delta', 'higher_group', 'flag']] # 'p_fdr',

#print(results[results['flag'] == 'significant and meaningful'])
display(results)

,measure,p_value,cliffs_delta,higher_group,flag
0,normalized_helpfulness_responses_qwen-3.5-27B,0.024874,0.151327,upper,significant difference
1,normalized_helpfulness_responses_llama-3.3-70B,0.006211,0.184579,upper,significant difference
2,normalized_helpfulness_responses_gemma-4-31B,0.037580,0.140270,upper,significant difference
3,normalized_helpfulness_responses_gpt-5.5,0.100207,0.110898,upper,no significant difference
4,humt_responses_qwen-3.5-27B,0.042366,-0.136933,low,significant difference
...,...,...,...,...,...
391,ling_avg_intensity_trust_gpt-5.5,0.008524,0.178108,upper,significant difference
392,ling_sentiment_score_gemma-4-31B,0.025478,0.150701,upper,significant difference
393,ling_sentiment_score_llama-3.3-70B,0.331072,0.065587,upper,no significant difference
394,ling_sentiment_score_qwen-3.5-27B,0.024049,0.152203,upper,significant difference
395,ling_sentiment_score_gpt-5.5,0.009953,0.174513,upper,significant difference

In [11]:
results.to_csv("upper_vs_low_differences.csv", index=False)

In [12]:
print(f"Number of MW-U tests: {len(results)}")
print(f'Significant differences between groups: {(len(results) - len(results[results["flag"] == "significant difference"]))/3}')

Number of MW-U tests: 396
Significant differences between groups: 102.66666666666667