### Aggregate data by user

In [ ]:
import pandas as pd

path = "human_likeness/human_likeness_all_models_clean.csv"

df = pd.read_csv(path, index_col=False)

df["user"] = df["id"].str.split("p").str[0]

df_mean = (
    df.groupby("user", as_index=False)
      .agg({
          "social_class": "first",
          **{col: "mean" for col in df.select_dtypes(include="number").columns}
      })
)

df_mean

,user,social_class,ses,humt_responses_qwen-3.5-27B,sociot_status_responses_qwen-3.5-27B,sociot_social_distance_responses_qwen-3.5-27B,sociot_gender_responses_qwen-3.5-27B,sociot_warmth_responses_qwen-3.5-27B,humt_responses_llama-3.3-70B,sociot_status_responses_llama-3.3-70B,...,humt_responses_gemma-4-31B,sociot_status_responses_gemma-4-31B,sociot_social_distance_responses_gemma-4-31B,sociot_gender_responses_gemma-4-31B,sociot_warmth_responses_gemma-4-31B,humt_responses_gpt-5.5,sociot_status_responses_gpt-5.5,sociot_social_distance_responses_gpt-5.5,sociot_gender_responses_gpt-5.5,sociot_warmth_responses_gpt-5.5
0,u1,upper,8.0,0.023095,-0.071759,0.073158,0.012857,0.025321,0.029543,-0.041021,...,0.035555,-0.073451,0.051445,0.003853,0.026388,0.026588,-0.071523,0.055837,-0.007194,0.032771
1,u10,middle,4.0,-0.020594,-0.060516,0.045889,0.024098,0.025284,0.025996,-0.063820,...,0.006662,-0.048932,0.028511,0.007058,0.005875,-0.013669,-0.053564,0.037663,0.018229,0.005928
2,u100,middle,5.0,0.001084,-0.045402,0.021460,-0.008554,-0.005779,0.013286,-0.036912,...,-0.002399,-0.069821,0.005718,0.005792,-0.005846,-0.019104,-0.049906,0.013498,-0.006666,0.028179
3,u101,middle,7.0,0.010785,-0.065784,0.059077,0.024418,0.030944,0.018736,-0.053815,...,0.029042,-0.044767,0.040755,0.006951,0.024419,0.036460,-0.066811,0.057152,0.022686,0.029121
4,u104,middle,5.0,-0.006946,0.005192,0.002667,0.029539,0.021212,-0.002470,-0.013435,...,0.019086,0.031629,0.074310,0.013099,0.006654,0.031680,-0.007167,0.075585,0.016762,0.020009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,u994,middle,4.0,0.020746,-0.048700,0.038126,0.002927,0.003825,0.020935,-0.068979,...,-0.010703,-0.058445,0.042872,0.021268,-0.009568,0.016200,-0.059726,0.043854,-0.009267,0.006764
728,u996,middle,6.0,0.006689,-0.043185,0.031113,0.005224,0.006343,0.009714,-0.074827,...,0.003875,-0.041901,0.045710,0.015735,0.026032,0.017302,-0.056645,0.059477,0.018574,0.031757
729,u997,middle,6.0,0.009798,-0.027808,0.023699,-0.045855,0.000295,0.038351,-0.059886,...,-0.015686,-0.016756,0.028371,0.032977,0.009479,0.024165,-0.066406,0.056226,0.020184,0.054182
730,u998,low,2.0,0.020126,-0.054790,0.041039,-0.000599,0.033423,0.028342,-0.060776,...,0.027581,-0.050413,0.051339,0.001814,0.043262,0.005279,-0.050731,0.047337,0.017544,0.037201
731,u999,upper,9.0,0.014284,-0.048089,0.027905,-0.007969,0.007494,0.004655,-0.047940,...,0.011038,-0.042151,0.033171,-0.008276,-0.000628,-0.010716,-0.040062,0.011102,-0.014943,0.003057

In [10]:
df_mean["social_class"].value_counts()

social_class
middle    406
low       214
upper     112
Name: count, dtype: int64

### Statistical Testing

In [1]:
import pandas as pd

path = "../all_metrics/all_metrics_per_user.csv"

df = pd.read_csv(path, index_col=False)

cols = list(df.columns)

In [3]:
# unused columns

exclude = ['user',
 'social_class',
 'gender',
 'gender_other',
 'age',
 'nationality',
 'ethnicity',
 'ethnicity_other',
 'marital',
 'marital_other',
 'language',
 'language_other',
 'religion',
 'religion_other',
 'education',
 'mum_education',
 'dad_education',
 'home',
 'home_other',
 'employment',
 'occupation',
 'mother_occupation',
 'father_occupation',
 'hobbies',
 'hobbies_other',
 'tech',
 'tech_other',
 'know_nlp',
 'know_nlp_other',
 'use_nlp',
 'use_nlp_other',
 'would_nlp',
 'would_nlp_other',
 'frequency_llm',
 'llm_use',
 'llm_other',
 'usecases',
 'usecases_other',
 'contexts',
 'contexts_other',
 'comments',
 'ses']

cols_rel = [col for col in cols if not col in exclude]

# exclude additional measures
cols_rel = [col for col in cols_rel if not col.startswith(("std", "ling", "helpfulness", "cplx"))]

# selection of complexity measures
#complexity = ["average_age_of_acquisition", 
#              "conceptual_graph_ontology_number_of_concpets",
#              "dale_chall_readability_score",
#              "gunning_fog_index",
#              "word_concreteness",
#              "average_cefr_level",
#              "mean_word_length",
#              "passive_constructions_density",
#              "connectives"]

# selection of linguistic features
linguistic = ["avg_valence", 
        "avg_arousal",
        "avg_dominance",
        "avg_intensity_anger",
        "avg_intensity_anticipation",
        "avg_intensity_disgust",
        "avg_intensity_fear",
        "avg_intensity_joy",
        "avg_intensity_sadness",
        "avg_intensity_surprise",
        "avg_intensity_trust",
        "sentiment_score"]

models = ["gemma-4-31B", "llama-3.3-70B", "qwen-3.5-27B", "gpt-5.5"]
ling = [f"ling_{l}_{m}" for l in linguistic for m in models]
#cplx = [f"cplx_{c}_{m}" for c in complexity for m in models]

cols_rel = cols_rel + ling

cols_rel

['normalized_helpfulness_responses_qwen-3.5-27B',
 'normalized_helpfulness_responses_llama-3.3-70B',
 'normalized_helpfulness_responses_gemma-4-31B',
 'normalized_helpfulness_responses_gpt-5.5',
 'humt_responses_qwen-3.5-27B',
 'sociot_status_responses_qwen-3.5-27B',
 'sociot_social_distance_responses_qwen-3.5-27B',
 'sociot_gender_responses_qwen-3.5-27B',
 'sociot_warmth_responses_qwen-3.5-27B',
 'humt_responses_llama-3.3-70B',
 'sociot_status_responses_llama-3.3-70B',
 'sociot_social_distance_responses_llama-3.3-70B',
 'sociot_gender_responses_llama-3.3-70B',
 'sociot_warmth_responses_llama-3.3-70B',
 'humt_responses_gemma-4-31B',
 'sociot_status_responses_gemma-4-31B',
 'sociot_social_distance_responses_gemma-4-31B',
 'sociot_gender_responses_gemma-4-31B',
 'sociot_warmth_responses_gemma-4-31B',
 'humt_responses_gpt-5.5',
 'sociot_status_responses_gpt-5.5',
 'sociot_social_distance_responses_gpt-5.5',
 'sociot_gender_responses_gpt-5.5',
 'sociot_warmth_responses_gpt-5.5',
 'syco_framing_qwen-3.5-27B',
 'syco_framing_llama-3.3-70B',
 'syco_framing_gemma-4-31B',
 'syco_framing_gpt-5.5',
 'syco_validation_qwen-3.5-27B',
 'syco_validation_llama-3.3-70B',
 'syco_validation_gemma-4-31B',
 'syco_validation_gpt-5.5',
 'syco_indirectness_qwen-3.5-27B',
 'syco_indirectness_llama-3.3-70B',
 'syco_indirectness_gemma-4-31B',
 'syco_indirectness_gpt-5.5',
 'ling_avg_valence_gemma-4-31B',
 'ling_avg_valence_llama-3.3-70B',
 'ling_avg_valence_qwen-3.5-27B',
 'ling_avg_valence_gpt-5.5',
 'ling_avg_arousal_gemma-4-31B',
 'ling_avg_arousal_llama-3.3-70B',
 'ling_avg_arousal_qwen-3.5-27B',
 'ling_avg_arousal_gpt-5.5',
 'ling_avg_dominance_gemma-4-31B',
 'ling_avg_dominance_llama-3.3-70B',
 'ling_avg_dominance_qwen-3.5-27B',
 'ling_avg_dominance_gpt-5.5',
 'ling_avg_intensity_anger_gemma-4-31B',
 'ling_avg_intensity_anger_llama-3.3-70B',
 'ling_avg_intensity_anger_qwen-3.5-27B',
 'ling_avg_intensity_anger_gpt-5.5',
 'ling_avg_intensity_anticipation_gemma-4-31B',
 'ling_avg_intensity_anticipation_llama-3.3-70B',
 'ling_avg_intensity_anticipation_qwen-3.5-27B',
 'ling_avg_intensity_anticipation_gpt-5.5',
 'ling_avg_intensity_disgust_gemma-4-31B',
 'ling_avg_intensity_disgust_llama-3.3-70B',
 'ling_avg_intensity_disgust_qwen-3.5-27B',
 'ling_avg_intensity_disgust_gpt-5.5',
 'ling_avg_intensity_fear_gemma-4-31B',
 'ling_avg_intensity_fear_llama-3.3-70B',
 'ling_avg_intensity_fear_qwen-3.5-27B',
 'ling_avg_intensity_fear_gpt-5.5',
 'ling_avg_intensity_joy_gemma-4-31B',
 'ling_avg_intensity_joy_llama-3.3-70B',
 'ling_avg_intensity_joy_qwen-3.5-27B',
 'ling_avg_intensity_joy_gpt-5.5',
 'ling_avg_intensity_sadness_gemma-4-31B',
 'ling_avg_intensity_sadness_llama-3.3-70B',
 'ling_avg_intensity_sadness_qwen-3.5-27B',
 'ling_avg_intensity_sadness_gpt-5.5',
 'ling_avg_intensity_surprise_gemma-4-31B',
 'ling_avg_intensity_surprise_llama-3.3-70B',
 'ling_avg_intensity_surprise_qwen-3.5-27B',
 'ling_avg_intensity_surprise_gpt-5.5',
 'ling_avg_intensity_trust_gemma-4-31B',
 'ling_avg_intensity_trust_llama-3.3-70B',
 'ling_avg_intensity_trust_qwen-3.5-27B',
 'ling_avg_intensity_trust_gpt-5.5',
 'ling_sentiment_score_gemma-4-31B',
 'ling_sentiment_score_llama-3.3-70B',
 'ling_sentiment_score_qwen-3.5-27B',
 'ling_sentiment_score_gpt-5.5']

### Kruskal-Wallis test 
We check whether the score distribution for each social class originates from the same population (i.e., is there a **significant difference between the 3 classes**?). Posthoc, we perform Dunn's test for pairwise comparisons of social classes and use Benjamin Hochberg correction for multiple tests.

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import scikit_posthocs as sp
from statsmodels.stats.multitest import multipletests

order = ['low', 'middle', 'upper']
measures = cols_rel

def cliffs_delta(x, y):
    x, y = np.array(x), np.array(y)
    diff = x[:, None] - y[None, :]
    return (np.sum(diff > 0) - np.sum(diff < 0)) / (len(x) * len(y))

rows = []
for measure in measures:
    sub = df.dropna(subset=[measure])
    groups = [sub.loc[sub['social_class'] == lvl, measure] for lvl in order]

    h_stat, p_omnibus = stats.kruskal(*groups)
    n = sum(len(g) for g in groups)
    eps_sq = h_stat / ((n**2 - 1) / (n + 1))

    # Dunn's test, Holm-corrected WITHIN this measure's 3 pairs
    dunn_p = sp.posthoc_dunn(sub, val_col=measure, group_col='social_class', p_adjust='holm')

    pairs = [('low', 'middle'), ('low', 'upper'), ('middle', 'upper')]
    for g1, g2 in pairs:
        x = sub.loc[sub['social_class'] == g1, measure]
        y = sub.loc[sub['social_class'] == g2, measure]
        delta = cliffs_delta(x, y)
        direction = g1 if delta > 0 else (g2 if delta < 0 else "tie")

        rows.append({
            'measure': measure,
            'p_omnibus': p_omnibus,
            'epsilon_squared': eps_sq,
            'comparison': f'{g1} vs {g2}',
            'dunn_p_holm': dunn_p.loc[g1, g2],   # significance for this pair
            'cliffs_delta': delta,               # magnitude + direction
            'higher_group': direction,
        })

results = pd.DataFrame(rows)

# Flag: is this specific pairwise comparison significant?
def flag_pair(row):
    if row['p_omnibus'] >= 0.05:
        return 'omnibus not significant'
    elif row['dunn_p_holm'] >= 0.05:
        return 'no significant difference (pair)'
    else:
        return 'significant difference (pair)'
    

results['pair_flag'] = results.apply(flag_pair, axis=1)

results['pair_flag'] = results.apply(flag_pair, axis=1)

results = results[['measure', 'p_omnibus', 'epsilon_squared',
                    'comparison', 'dunn_p_holm', 'cliffs_delta', 'higher_group', 'pair_flag']]

results

,measure,p_omnibus,epsilon_squared,comparison,dunn_p_holm,cliffs_delta,higher_group,pair_flag
0,normalized_helpfulness_responses_qwen-3.5-27B,0.112036,0.005989,low vs middle,0.332234,-0.052208,middle,omnibus not significant
1,normalized_helpfulness_responses_qwen-3.5-27B,0.112036,0.005989,low vs upper,0.110884,-0.151327,upper,omnibus not significant
2,normalized_helpfulness_responses_qwen-3.5-27B,0.112036,0.005989,middle vs upper,0.332234,-0.079719,upper,omnibus not significant
3,normalized_helpfulness_responses_llama-3.3-70B,0.031422,0.009467,low vs middle,0.211209,-0.073316,middle,no significant difference (pair)
4,normalized_helpfulness_responses_llama-3.3-70B,0.031422,0.009467,low vs upper,0.027489,-0.184579,upper,significant difference (pair)
...,...,...,...,...,...,...,...,...
1183,ling_sentiment_score_qwen-3.5-27B,0.077464,0.006998,low vs upper,0.088635,-0.152203,upper,omnibus not significant
1184,ling_sentiment_score_qwen-3.5-27B,0.077464,0.006998,middle vs upper,0.093044,-0.119810,upper,omnibus not significant
1185,ling_sentiment_score_gpt-5.5,0.041350,0.008764,low vs middle,0.252702,-0.054897,middle,no significant difference (pair)
1186,ling_sentiment_score_gpt-5.5,0.041350,0.008764,low vs upper,0.034860,-0.174513,upper,significant difference (pair)
1187,ling_sentiment_score_gpt-5.5,0.041350,0.008764,middle vs upper,0.127825,-0.112680,upper,no significant difference (pair)

In [6]:
results.to_csv("all_group_differences.csv", index=False)

In [9]:
print(f"Number of KW tests: {len(results)/3}")
print(f'Significant differences between groups: {(len(results) - len(results[results["pair_flag"] == "omnibus not significant"]))/3}')
print()
print(f'Significant differences between pairs of groups: {len(results[results["pair_flag"] == "significant difference (pair)"])} out of {len(results)}')

Number of KW tests: 396.0
Significant differences between groups: 109.0

Significant differences between pairs of groups: 156 out of 1188

### Mann-Whitney-U-test
We also test whether there is a significant difference between only the **upper** and **lower** class by using Mann-Whitney-U-test.

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.multitest import multipletests

measures = cols_rel

def cliffs_delta(x, y):
    x, y = np.array(x), np.array(y)
    diff = x[:, None] - y[None, :]
    return (np.sum(diff > 0) - np.sum(diff < 0)) / (len(x) * len(y))

rows = []
for measure in measures:
    sub = df.dropna(subset=[measure])
    x = sub.loc[sub['social_class'] == 'upper', measure]
    y = sub.loc[sub['social_class'] == 'low', measure]

    stat, p = stats.mannwhitneyu(x, y, alternative='two-sided')
    delta = cliffs_delta(x, y)
    direction = 'upper' if delta > 0 else ('low' if delta < 0 else 'tie')

    rows.append({
        'measure': measure,
        'p_value': p,
        'cliffs_delta': delta,
        'higher_group': direction,
    })

results = pd.DataFrame(rows)

# Simple flag combining significance + meaningful magnitude
def flag(row):
    if row['p_value'] >= 0.05:
        return 'no significant difference'
    else:
        return "significant difference"

results['flag'] = results.apply(flag, axis=1)

results = results[['measure', 'p_value', 'cliffs_delta', 'higher_group', 'flag']]

display(results)

,measure,p_value,cliffs_delta,higher_group,flag
0,normalized_helpfulness_responses_qwen-3.5-27B,0.024874,0.151327,upper,significant difference
1,normalized_helpfulness_responses_llama-3.3-70B,0.006211,0.184579,upper,significant difference
2,normalized_helpfulness_responses_gemma-4-31B,0.037580,0.140270,upper,significant difference
3,normalized_helpfulness_responses_gpt-5.5,0.100207,0.110898,upper,no significant difference
4,humt_responses_qwen-3.5-27B,0.042366,-0.136933,low,significant difference
...,...,...,...,...,...
391,ling_avg_intensity_trust_gpt-5.5,0.008524,0.178108,upper,significant difference
392,ling_sentiment_score_gemma-4-31B,0.025478,0.150701,upper,significant difference
393,ling_sentiment_score_llama-3.3-70B,0.331072,0.065587,upper,no significant difference
394,ling_sentiment_score_qwen-3.5-27B,0.024049,0.152203,upper,significant difference
395,ling_sentiment_score_gpt-5.5,0.009953,0.174513,upper,significant difference

In [11]:
results.to_csv("upper_vs_low_differences.csv", index=False)

In [12]:
print(f"Number of MW-U tests: {len(results)}")
print(f'Significant differences between groups: {(len(results) - len(results[results["flag"] == "significant difference"]))/3}')

Number of MW-U tests: 396
Significant differences between groups: 102.66666666666667

# Analysis

In [6]:
# add in interesting complexity measures
meas = ["cplx_syllables_per_word", "cplx_average_age_of_acquisition", "cplx_adversative_connectives"]
models = ["gemma-4-31B", "llama-3.3-70B", "qwen-3.5-27B", "gpt-5.5"]

comp_cols = [f"{m}_{model}" for m in meas for model in models]
comp_cols

['cplx_syllables_per_word_gemma-4-31B',
 'cplx_syllables_per_word_llama-3.3-70B',
 'cplx_syllables_per_word_qwen-3.5-27B',
 'cplx_syllables_per_word_gpt-5.5',
 'cplx_average_age_of_acquisition_gemma-4-31B',
 'cplx_average_age_of_acquisition_llama-3.3-70B',
 'cplx_average_age_of_acquisition_qwen-3.5-27B',
 'cplx_average_age_of_acquisition_gpt-5.5',
 'cplx_adversative_connectives_gemma-4-31B',
 'cplx_adversative_connectives_llama-3.3-70B',
 'cplx_adversative_connectives_qwen-3.5-27B',
 'cplx_adversative_connectives_gpt-5.5']

### Upper vs lower 

For each model, show for which measures there is a significant difference between the **upper** and **lower** social class (p < 0.05).

In [7]:
import pandas as pd

res_ul = pd.read_csv("upper_vs_low_differences.csv")
res_ul = res_ul[
    ~res_ul["measure"].str.startswith("cplx", na=False)
    | res_ul["measure"].isin(comp_cols)
]

models = ["gemma-4-31B", "llama-3.3-70B", "qwen-3.5-27B", "gpt-5.5"]

for m in models:
    print(m)
    res_model = res_ul[res_ul["measure"].str.endswith(m)]
    sign = res_model[res_model["flag"] == "significant difference"]
    display(sign)
    print(len(res_model))
    print(len(sign))
    print()

gemma-4-31B

,measure,p_value,cliffs_delta,higher_group,flag
2,normalized_helpfulness_responses_gemma-4-31B,0.037580,0.140270,upper,significant difference
17,sociot_gender_responses_gemma-4-31B,0.022035,-0.154456,low,significant difference
30,cplx_average_age_of_acquisition_gemma-4-31B,0.000675,0.229306,upper,significant difference
86,cplx_syllables_per_word_gemma-4-31B,0.000101,0.262266,upper,significant difference
356,ling_avg_dominance_gemma-4-31B,0.000198,0.251001,upper,significant difference
360,ling_avg_intensity_anger_gemma-4-31B,0.026471,-0.149700,low,significant difference
372,ling_avg_intensity_fear_gemma-4-31B,0.032552,-0.144192,low,significant difference
388,ling_avg_intensity_trust_gemma-4-31B,0.042492,0.136849,upper,significant difference
392,ling_sentiment_score_gemma-4-31B,0.025478,0.150701,upper,significant difference

24
9

llama-3.3-70B

,measure,p_value,cliffs_delta,higher_group,flag
1,normalized_helpfulness_responses_llama-3.3-70B,0.006211,0.184579,upper,significant difference
186,cplx_average_age_of_acquisition_llama-3.3-70B,0.000013,0.294643,upper,significant difference
242,cplx_syllables_per_word_llama-3.3-70B,0.000007,0.302654,upper,significant difference
337,syco_framing_llama-3.3-70B,0.046082,-0.085072,low,significant difference
357,ling_avg_dominance_llama-3.3-70B,0.000002,0.322180,upper,significant difference

24
5

qwen-3.5-27B

,measure,p_value,cliffs_delta,higher_group,flag
0,normalized_helpfulness_responses_qwen-3.5-27B,0.024874,0.151327,upper,significant difference
4,humt_responses_qwen-3.5-27B,0.042366,-0.136933,low,significant difference
264,cplx_average_age_of_acquisition_qwen-3.5-27B,0.000003,0.315087,upper,significant difference
320,cplx_syllables_per_word_qwen-3.5-27B,0.000004,0.310414,upper,significant difference
340,syco_validation_qwen-3.5-27B,0.019541,-0.090746,low,significant difference
358,ling_avg_dominance_qwen-3.5-27B,0.000008,0.301819,upper,significant difference
394,ling_sentiment_score_qwen-3.5-27B,0.024049,0.152203,upper,significant difference

24
7

gpt-5.5

,measure,p_value,cliffs_delta,higher_group,flag
22,sociot_gender_responses_gpt-5.5,6.767997e-03,-0.183352,low,significant difference
108,cplx_average_age_of_acquisition_gpt-5.5,9.125569e-05,0.264899,upper,significant difference
164,cplx_syllables_per_word_gpt-5.5,3.504385e-06,0.314046,upper,significant difference
343,syco_validation_gpt-5.5,2.157717e-02,-0.082235,low,significant difference
351,ling_avg_valence_gpt-5.5,1.275256e-02,0.168633,upper,significant difference
355,ling_avg_arousal_gpt-5.5,1.769754e-02,0.160597,upper,significant difference
359,ling_avg_dominance_gpt-5.5,1.556137e-09,0.408789,upper,significant difference
367,ling_avg_intensity_anticipation_gpt-5.5,1.960939e-03,0.209618,upper,significant difference
391,ling_avg_intensity_trust_gpt-5.5,8.524175e-03,0.178108,upper,significant difference
395,ling_sentiment_score_gpt-5.5,9.952963e-03,0.174513,upper,significant difference

24
10

### All groups
For each model, show for which measures there is a significant difference between the **three social classes** (p < 0.05).

In [8]:
res_ul = pd.read_csv("/mnt/homes/marlene/SEAL/seal/evaluation/statistical_testing/all_group_differences.csv")
res_ul = res_ul[
    ~res_ul["measure"].str.startswith("cplx", na=False)
    | res_ul["measure"].isin(comp_cols)
]

models = ["gemma-4-31B", "llama-3.3-70B", "qwen-3.5-27B", "gpt-5.5"]

for m in models:
    print(m)
    res_model = res_ul[res_ul["measure"].str.endswith(m)]

    sign = res_model[res_model["pair_flag"] != "omnibus not significant"]

    sign = (
        sign[["measure", "p_omnibus"]]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    display(sign)
    print(len(sign))
    print(len(res_model))
    print()

gemma-4-31B

                                       measure  p_omnibus
0     cplx_adversative_connectives_gemma-4-31B   0.021722
1  cplx_average_age_of_acquisition_gemma-4-31B   0.003915
2          cplx_syllables_per_word_gemma-4-31B   0.001805
3                     syco_framing_gemma-4-31B   0.000188
4                  syco_validation_gemma-4-31B   0.000004
5                syco_indirectness_gemma-4-31B   0.026740
6               ling_avg_dominance_gemma-4-31B   0.000774
7          ling_avg_intensity_fear_gemma-4-31B   0.012757

8
72

llama-3.3-70B

                                          measure  p_omnibus
0  normalized_helpfulness_responses_llama-3.3-70B   0.031422
1      cplx_adversative_connectives_llama-3.3-70B   0.013845
2   cplx_average_age_of_acquisition_llama-3.3-70B   0.000283
3           cplx_syllables_per_word_llama-3.3-70B   0.000225
4                      syco_framing_llama-3.3-70B   0.009865
5                   syco_validation_llama-3.3-70B   0.000008
6                 syco_indirectness_llama-3.3-70B   0.010045
7                  ling_avg_arousal_llama-3.3-70B   0.042884
8                ling_avg_dominance_llama-3.3-70B   0.000022

9
72

qwen-3.5-27B

                                        measure  p_omnibus
0     cplx_adversative_connectives_qwen-3.5-27B   0.031003
1  cplx_average_age_of_acquisition_qwen-3.5-27B   0.000042
2          cplx_syllables_per_word_qwen-3.5-27B   0.000185
3                     syco_framing_qwen-3.5-27B   0.000001
4                  syco_validation_qwen-3.5-27B   0.000002
5                syco_indirectness_qwen-3.5-27B   0.000505
6               ling_avg_dominance_qwen-3.5-27B   0.000182

7
72

gpt-5.5

                                    measure     p_omnibus
0      cplx_adversative_connectives_gpt-5.5  7.737609e-04
1   cplx_average_age_of_acquisition_gpt-5.5  1.212431e-03
2           cplx_syllables_per_word_gpt-5.5  1.165338e-04
3                      syco_framing_gpt-5.5  1.873407e-03
4                   syco_validation_gpt-5.5  2.610182e-06
5                 syco_indirectness_gpt-5.5  1.305774e-04
6                  ling_avg_valence_gpt-5.5  2.812566e-02
7                  ling_avg_arousal_gpt-5.5  2.425291e-02
8                ling_avg_dominance_gpt-5.5  4.026536e-08
9   ling_avg_intensity_anticipation_gpt-5.5  5.798768e-03
10             ling_sentiment_score_gpt-5.5  4.134995e-02

11
72