### Get the measures of all models

In [29]:
import pandas as pd

path = "../all_metrics/final_metrics_per_user.csv"

df = pd.read_csv(path, index_col=False)

cols = list(df.columns)

In [30]:
# exlude demographic columns

exclude = ['user',
 'gender',
 'gender_other',
 'age',
 'nationality',
 'ethnicity',
 'ethnicity_other',
 'marital',
 'marital_other',
 'language',
 'language_other',
 'religion',
 'religion_other',
 'education',
 'mum_education',
 'dad_education',
 'home',
 'home_other',
 'employment',
 'occupation',
 'mother_occupation',
 'father_occupation',
 'hobbies',
 'hobbies_other',
 'tech',
 'tech_other',
 'know_nlp',
 'know_nlp_other',
 'use_nlp',
 'use_nlp_other',
 'would_nlp',
 'would_nlp_other',
 'frequency_llm',
 'llm_use',
 'llm_other',
 'usecases',
 'usecases_other',
 'contexts',
 'contexts_other',
 'comments',
 'ses']

keep = [col for col in cols if not col in exclude]
df = df[keep]

df

,social_class,normalized_helpfulness_responses_qwen-3.5-27B,normalized_helpfulness_responses_llama-3.3-70B,normalized_helpfulness_responses_gemma-4-31B,normalized_helpfulness_responses_gpt-5.5,humt_responses_qwen-3.5-27B,sociot_status_responses_qwen-3.5-27B,sociot_social_distance_responses_qwen-3.5-27B,sociot_gender_responses_qwen-3.5-27B,sociot_warmth_responses_qwen-3.5-27B,...,cplx_syllables_per_word_qwen-3.5-27B,cplx_syllables_per_word_gpt-5.5,cplx_adversative_connectives_gemma-4-31B,cplx_adversative_connectives_llama-3.3-70B,cplx_adversative_connectives_qwen-3.5-27B,cplx_adversative_connectives_gpt-5.5,cplx_negations_density_gemma-4-31B,cplx_negations_density_llama-3.3-70B,cplx_negations_density_qwen-3.5-27B,cplx_negations_density_gpt-5.5
0,upper,-0.590969,0.100678,-0.670983,-0.053921,0.023095,-0.071759,0.073158,0.012857,0.025321,...,1.897301,1.588075,0.000000,0.5,0.000000,0.000000,0.004734,0.001931,0.000000,0.003125
1,middle,-0.429432,-0.329389,-0.702419,-0.101009,-0.020594,-0.060516,0.045889,0.024098,0.025284,...,1.416700,1.386410,1.666667,1.0,2.333333,0.333333,0.007666,0.005785,0.005171,0.001610
2,middle,-0.267895,0.400629,0.306137,0.340518,0.001084,-0.045402,0.021460,-0.008554,-0.005779,...,1.569083,1.481496,0.000000,1.0,2.000000,0.000000,0.001366,0.000000,0.002725,0.000000
3,middle,-0.373399,-0.537540,-0.965112,-0.217476,0.010785,-0.065784,0.059077,0.024418,0.030944,...,1.489309,1.445867,1.000000,0.8,0.800000,0.800000,0.002254,0.004899,0.005927,0.000656
4,middle,-1.121014,-1.222394,-1.297814,-0.585955,-0.006946,0.005192,0.002667,0.029539,0.021212,...,1.448980,1.312500,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,middle,0.494360,-0.318432,0.428100,-0.061259,0.020746,-0.048700,0.038126,0.002927,0.003825,...,1.659666,1.627193,1.000000,0.5,0.000000,0.500000,0.005556,0.005682,0.007286,0.000000
728,middle,0.529696,0.363649,0.669189,0.503797,0.006689,-0.043185,0.031113,0.005224,0.006343,...,1.669965,1.571245,1.500000,1.0,1.500000,4.500000,0.001276,0.000000,0.002500,0.005747
729,middle,-0.772699,-1.275810,-1.320505,-0.452029,0.009798,-0.027808,0.023699,-0.045855,0.000295,...,1.642857,1.428571,0.000000,0.0,1.000000,0.000000,0.000000,0.042105,0.038961,0.000000
730,low,0.958780,1.556981,1.260283,1.248645,0.020126,-0.054790,0.041039,-0.000599,0.033423,...,1.573513,1.667087,3.000000,0.8,2.800000,2.200000,0.002517,0.004155,0.004905,0.002046
731,upper,1.344450,0.910135,1.252341,0.782473,0.014284,-0.048089,0.027905,-0.007969,0.007494,...,1.753242,1.810319,2.300000,0.7,2.000000,0.600000,0.003933,0.001634,0.004510,0.004561

In [31]:
# complexity measures
complexity = ["average_age_of_acquisition",
              "syllables_per_word",
              "adversative_connectives",
              "negations_density"] 


# linguistic features
linguistic = ["avg_valence", 
        "avg_arousal",
        "avg_dominance", 
        "avg_intensity_anger", 
        "avg_intensity_anticipation", 
        "avg_intensity_disgust", 
        "avg_intensity_fear", 
        "avg_intensity_joy", 
        "avg_intensity_sadness", 
        "avg_intensity_surprise", 
        "avg_intensity_trust", 
        "sentiment_score"] 

# all other measures
others = ["normalized_helpfulness_responses",
          'humt_responses',
          'sociot_status_responses',
          'sociot_social_distance_responses',
          'sociot_gender_responses',
          'sociot_warmth_responses',
          'syco_framing',
          'syco_validation',
          'syco_indirectness']

models = ["gemma-4-31B", "llama-3.3-70B", "qwen-3.5-27B", "gpt-5.5"]
ling = [f"ling_{l}_{m}" for l in linguistic for m in models]
cplx = [f"cplx_{c}_{m}" for c in complexity for m in models]
oth = [f"{o}_{m}" for o in others for m in models]

measures = ling + cplx + oth

measures

['ling_avg_valence_gemma-4-31B',
 'ling_avg_valence_llama-3.3-70B',
 'ling_avg_valence_qwen-3.5-27B',
 'ling_avg_valence_gpt-5.5',
 'ling_avg_arousal_gemma-4-31B',
 'ling_avg_arousal_llama-3.3-70B',
 'ling_avg_arousal_qwen-3.5-27B',
 'ling_avg_arousal_gpt-5.5',
 'ling_avg_dominance_gemma-4-31B',
 'ling_avg_dominance_llama-3.3-70B',
 'ling_avg_dominance_qwen-3.5-27B',
 'ling_avg_dominance_gpt-5.5',
 'ling_avg_intensity_anger_gemma-4-31B',
 'ling_avg_intensity_anger_llama-3.3-70B',
 'ling_avg_intensity_anger_qwen-3.5-27B',
 'ling_avg_intensity_anger_gpt-5.5',
 'ling_avg_intensity_anticipation_gemma-4-31B',
 'ling_avg_intensity_anticipation_llama-3.3-70B',
 'ling_avg_intensity_anticipation_qwen-3.5-27B',
 'ling_avg_intensity_anticipation_gpt-5.5',
 'ling_avg_intensity_disgust_gemma-4-31B',
 'ling_avg_intensity_disgust_llama-3.3-70B',
 'ling_avg_intensity_disgust_qwen-3.5-27B',
 'ling_avg_intensity_disgust_gpt-5.5',
 'ling_avg_intensity_fear_gemma-4-31B',
 'ling_avg_intensity_fear_llama-3.3-70B',
 'ling_avg_intensity_fear_qwen-3.5-27B',
 'ling_avg_intensity_fear_gpt-5.5',
 'ling_avg_intensity_joy_gemma-4-31B',
 'ling_avg_intensity_joy_llama-3.3-70B',
 'ling_avg_intensity_joy_qwen-3.5-27B',
 'ling_avg_intensity_joy_gpt-5.5',
 'ling_avg_intensity_sadness_gemma-4-31B',
 'ling_avg_intensity_sadness_llama-3.3-70B',
 'ling_avg_intensity_sadness_qwen-3.5-27B',
 'ling_avg_intensity_sadness_gpt-5.5',
 'ling_avg_intensity_surprise_gemma-4-31B',
 'ling_avg_intensity_surprise_llama-3.3-70B',
 'ling_avg_intensity_surprise_qwen-3.5-27B',
 'ling_avg_intensity_surprise_gpt-5.5',
 'ling_avg_intensity_trust_gemma-4-31B',
 'ling_avg_intensity_trust_llama-3.3-70B',
 'ling_avg_intensity_trust_qwen-3.5-27B',
 'ling_avg_intensity_trust_gpt-5.5',
 'ling_sentiment_score_gemma-4-31B',
 'ling_sentiment_score_llama-3.3-70B',
 'ling_sentiment_score_qwen-3.5-27B',
 'ling_sentiment_score_gpt-5.5',
 'cplx_average_age_of_acquisition_gemma-4-31B',
 'cplx_average_age_of_acquisition_llama-3.3-70B',
 'cplx_average_age_of_acquisition_qwen-3.5-27B',
 'cplx_average_age_of_acquisition_gpt-5.5',
 'cplx_syllables_per_word_gemma-4-31B',
 'cplx_syllables_per_word_llama-3.3-70B',
 'cplx_syllables_per_word_qwen-3.5-27B',
 'cplx_syllables_per_word_gpt-5.5',
 'cplx_adversative_connectives_gemma-4-31B',
 'cplx_adversative_connectives_llama-3.3-70B',
 'cplx_adversative_connectives_qwen-3.5-27B',
 'cplx_adversative_connectives_gpt-5.5',
 'cplx_negations_density_gemma-4-31B',
 'cplx_negations_density_llama-3.3-70B',
 'cplx_negations_density_qwen-3.5-27B',
 'cplx_negations_density_gpt-5.5',
 'normalized_helpfulness_responses_gemma-4-31B',
 'normalized_helpfulness_responses_llama-3.3-70B',
 'normalized_helpfulness_responses_qwen-3.5-27B',
 'normalized_helpfulness_responses_gpt-5.5',
 'humt_responses_gemma-4-31B',
 'humt_responses_llama-3.3-70B',
 'humt_responses_qwen-3.5-27B',
 'humt_responses_gpt-5.5',
 'sociot_status_responses_gemma-4-31B',
 'sociot_status_responses_llama-3.3-70B',
 'sociot_status_responses_qwen-3.5-27B',
 'sociot_status_responses_gpt-5.5',
 'sociot_social_distance_responses_gemma-4-31B',
 'sociot_social_distance_responses_llama-3.3-70B',
 'sociot_social_distance_responses_qwen-3.5-27B',
 'sociot_social_distance_responses_gpt-5.5',
 'sociot_gender_responses_gemma-4-31B',
 'sociot_gender_responses_llama-3.3-70B',
 'sociot_gender_responses_qwen-3.5-27B',
 'sociot_gender_responses_gpt-5.5',
 'sociot_warmth_responses_gemma-4-31B',
 'sociot_warmth_responses_llama-3.3-70B',
 'sociot_warmth_responses_qwen-3.5-27B',
 'sociot_warmth_responses_gpt-5.5',
 'syco_framing_gemma-4-31B',
 'syco_framing_llama-3.3-70B',
 'syco_framing_qwen-3.5-27B',
 'syco_framing_gpt-5.5',
 'syco_validation_gemma-4-31B',
 'syco_validation_llama-3.3-70B',
 'syco_validation_qwen-3.5-27B',
 'syco_validation_gpt-5.5',
 'syco_indirectness_gemma-4-31B',
 'syco_indirectness_llama-3.3-70B',
 'syco_indirectness_qwen-3.5-27B',
 'syco_indirectness_gpt-5.5']

### Kruskal-Wallis test 
We check whether the score distribution for each social class originates from the same population (i.e., is there a **significant difference between the 3 classes**?). Correct for the number of test (i.e., measures) per model using Benjamin-Hochberg correction.

In [32]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.multitest import multipletests

order = ['low', 'middle', 'upper']
models = ["qwen-3.5-27B", "llama-3.3-70B", "gemma-4-31B", "gpt-5.5"]

def get_model(col, models):
    for m in models:
        if col.endswith(m):
            return m
    return None

rows = []
for measure in measures:
    model = get_model(measure, models)
    if model is None:
        continue

    sub = df.dropna(subset=[measure])
    groups = [sub.loc[sub['social_class'] == lvl, measure] for lvl in order]

    #if any(len(g) == 0 for g in groups):
    #    continue

    h_stat, p_omnibus = stats.kruskal(*groups)
    n = sum(len(g) for g in groups)
    eps_sq = h_stat / ((n**2 - 1) / (n + 1))

    rows.append({
        'model': model,
        'measure': measure,
        'p_omnibus': p_omnibus,
        'epsilon_squared': eps_sq,

    })

results = pd.DataFrame(rows)

results['p_omnibus_fdr'] = np.nan
results['significant_fdr'] = False

for model in models:
    mask = results['model'] == model
    pvals = results.loc[mask, 'p_omnibus'].values
    if len(pvals) == 0:
        continue
    reject, p_adj, _, _ = multipletests(pvals, alpha=0.05, method='fdr_bh')
    results.loc[mask, 'p_omnibus_fdr'] = p_adj
    results.loc[mask, 'significant_fdr'] = reject

results = results[['model', 'measure', 'p_omnibus', 'p_omnibus_fdr', 'significant_fdr', 'epsilon_squared']]
results = results.sort_values(['model', 'p_omnibus_fdr'])

results

,model,measure,p_omnibus,p_omnibus_fdr,significant_fdr,epsilon_squared
92,gemma-4-31B,syco_validation_gemma-4-31B,0.000004,0.000094,True,0.034169
60,gemma-4-31B,cplx_negations_density_gemma-4-31B,0.000021,0.000268,True,0.029413
88,gemma-4-31B,syco_framing_gemma-4-31B,0.000188,0.001566,True,0.023473
8,gemma-4-31B,ling_avg_dominance_gemma-4-31B,0.000774,0.004840,True,0.019599
52,gemma-4-31B,cplx_syllables_per_word_gemma-4-31B,0.001805,0.009023,True,0.017284
...,...,...,...,...,...,...
86,qwen-3.5-27B,sociot_warmth_responses_qwen-3.5-27B,0.432015,0.514304,False,0.002296
74,qwen-3.5-27B,sociot_status_responses_qwen-3.5-27B,0.541280,0.615091,False,0.001679
38,qwen-3.5-27B,ling_avg_intensity_surprise_qwen-3.5-27B,0.581165,0.631701,False,0.001485
34,qwen-3.5-27B,ling_avg_intensity_sadness_qwen-3.5-27B,0.845372,0.880595,False,0.000460
14,qwen-3.5-27B,ling_avg_intensity_anger_qwen-3.5-27B,0.987080,0.987080,False,0.000036

In [33]:
results.to_csv("all_group_differences.csv", index=False)

# Analysis

### All groups
For each model, show for which measures there is a significant difference between the **three social classes** (p < 0.05).

In [28]:
results = results[['model', 'measure', 'p_omnibus', 'p_omnibus_fdr', 'significant_fdr', 'epsilon_squared']]
results = results.sort_values(['model', 'p_omnibus_fdr'])

# ---- overall summary ----
n_sig = results['significant_fdr'].sum()
n_total = len(results)
print(f"Significant tests (FDR-corrected): {n_sig}/{n_total}\n")

summary = results.groupby('model')['significant_fdr'].agg(['sum', 'count'])
summary.columns = ['n_significant', 'n_total']
print(summary)

# ---- significant measures with p-values, by model ----
print("\nSignificant measures (FDR-corrected), by model:")
for model in models:
    model_sig = results[(results['model'] == model) & (results['significant_fdr'])].sort_values('p_omnibus_fdr')
    print(f"\n  {model}:")
    if model_sig.empty:
        print("    none")
    else:
        print(model_sig[['measure', 'p_omnibus', 'p_omnibus_fdr', 'epsilon_squared']]
              .to_string(index=False))


#results

Significant tests (FDR-corrected): 31/100

               n_significant  n_total
model
gemma-4-31B                7       25
gpt-5.5                    9       25
llama-3.3-70B              8       25
qwen-3.5-27B               7       25

Significant measures (FDR-corrected), by model:

  qwen-3.5-27B:
                                     measure  p_omnibus  p_omnibus_fdr  epsilon_squared
                   syco_framing_qwen-3.5-27B   0.000001       0.000026         0.037226
                syco_validation_qwen-3.5-27B   0.000002       0.000026         0.035796
cplx_average_age_of_acquisition_qwen-3.5-27B   0.000042       0.000353         0.027546
             ling_avg_dominance_qwen-3.5-27B   0.000182       0.000923         0.023556
        cplx_syllables_per_word_qwen-3.5-27B   0.000185       0.000923         0.023522
              syco_indirectness_qwen-3.5-27B   0.000505       0.002104         0.020769
         cplx_negations_density_qwen-3.5-27B   0.007030       0.025108         0.013564

  llama-3.3-70B:
                                      measure  p_omnibus  p_omnibus_fdr  epsilon_squared
                syco_validation_llama-3.3-70B   0.000008       0.000193         0.032208
             ling_avg_dominance_llama-3.3-70B   0.000022       0.000280         0.029293
cplx_average_age_of_acquisition_llama-3.3-70B   0.000283       0.001771         0.022380
        cplx_syllables_per_word_llama-3.3-70B   0.000225       0.001771         0.022983
         cplx_negations_density_llama-3.3-70B   0.000702       0.003508         0.019869
                   syco_framing_llama-3.3-70B   0.009865       0.035874         0.012637
              syco_indirectness_llama-3.3-70B   0.010045       0.035874         0.012587
   cplx_adversative_connectives_llama-3.3-70B   0.013845       0.043264         0.011710

  gemma-4-31B:
                                    measure  p_omnibus  p_omnibus_fdr  epsilon_squared
                syco_validation_gemma-4-31B   0.000004       0.000094         0.034169
         cplx_negations_density_gemma-4-31B   0.000021       0.000268         0.029413
                   syco_framing_gemma-4-31B   0.000188       0.001566         0.023473
             ling_avg_dominance_gemma-4-31B   0.000774       0.004840         0.019599
        cplx_syllables_per_word_gemma-4-31B   0.001805       0.009023         0.017284
cplx_average_age_of_acquisition_gemma-4-31B   0.003915       0.016311         0.015186
        ling_avg_intensity_fear_gemma-4-31B   0.012757       0.045562         0.011933

  gpt-5.5:
                                measure    p_omnibus  p_omnibus_fdr  epsilon_squared
             ling_avg_dominance_gpt-5.5 4.026536e-08   6.402879e-07         0.046844
         cplx_negations_density_gpt-5.5 5.122303e-08   6.402879e-07         0.046245
                syco_validation_gpt-5.5 2.610182e-06   2.175152e-05         0.035174
        cplx_syllables_per_word_gpt-5.5 1.165338e-04   6.528871e-04         0.024951
              syco_indirectness_gpt-5.5 1.305774e-04   6.528871e-04         0.024469
   cplx_adversative_connectives_gpt-5.5 7.737609e-04   3.224004e-03         0.019709
cplx_average_age_of_acquisition_gpt-5.5 1.212431e-03   4.330110e-03         0.018499
                   syco_framing_gpt-5.5 1.873407e-03   5.854398e-03         0.017182
ling_avg_intensity_anticipation_gpt-5.5 5.798768e-03   1.610769e-02         0.014168